name: Code-Analysis
on:
  push:
    branches:
      - main
      - fix/*
      - release/*
      - feature/*
    tags:
      - '*'
  pull_request:
    branches: ["main"]
jobs:
  analysis:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 6 LTS
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    - name: Setup .NET 8 (Preview)
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
        include-prerelease: true
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 1.17
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~\sonar\cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache SonarCloud scanner
      id: cache-sonar-scanner
      uses: actions/cache@v1
      with:
        path: .\.sonar\scanner
        key: ${{ runner.os }}-sonar-scanner
        restore-keys: ${{ runner.os }}-sonar-scanner
    - name: Install SonarCloud scanner
      if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
      shell: powershell
      run: |
        New-Item -Path .\.sonar\scanner -ItemType Directory
        dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
        dotnet tool install --global dotnet-coverage
    - name: Begin Analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      shell: powershell
      run: |
        .\.sonar\scanner\dotnet-sonarscanner begin /k:"alexandrejulien_aspnetcore-security-headers-addons" /o:"alexandrejulien" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml  
    - name: Restore dependencies
      run: dotnet restore ./AspNetCore.SecurityHeaders.Addons.sln
    - name: Build
      run: dotnet build ./AspNetCore.SecurityHeaders.Addons.sln --no-restore --configuration Debug
    - name: Test
      shell: powershell
      run: |
        dotnet tool install --global dotnet-coverage
        dotnet-coverage collect 'dotnet test ./AspNetCore.SecurityHeaders.Addons.sln' -f xml  -o 'coverage.xml'
    - name: End Analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      shell: powershell
      run: |
        .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
